#!/bin/bash

source "./scripts/helpers.sh"

new_migrations=$(
	( git ls-tree --full-tree --name-only 'HEAD@{1}' scripts/migrations/
	git ls-tree --full-tree --name-only 'HEAD' scripts/migrations/ ) | sort -u)

for m in "$new_migrations"; do
	[ ! -x "$m" ] && continue
	start_job "Lance le script de migration $m"
	"$m"
	end_job
done
